include:
  - template: Jobs/Build.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
- generate
- build
- test
- deploy

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules
    - dist

generate:
  image: openapitools/openapi-generator-cli:v5.2.0
  stage: generate
  script:
    - >
      java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate
      -i ./spec/openapi-v1.yaml
      -g typescript-axios
      -o ./src/generated
    - apt update
    - apt install git -y
    - git config --global user.name "Mr.Roboto 🤖"
    - git config --global user.email "mrRoboto@blockdaemon.com"
    - git add ./src/generated
    - git commit -m "UB-00 Updating generated code with changes from ${CI_JOB_ID}" || true
    - git push http://gitlab-ci-token:${AUTH_TOKEN_UBIQUITY_TS_CLIENT}@gitlab.com/Blockdaemon/ubiquity/ubiquity-ts-client.git HEAD:master || true
  only:
    refs:
      - master
    changes:
      - spec/openapi-v1.yaml

build:
  image: node:15-alpine
  stage: build
  script:
    - npm install
    - npm run build

test:
  image: node:15-alpine
  stage: test
  script:
    - npm install
    - npm run build
    - npm run test

deploy:
  image: node:15-alpine
  stage: deploy
  script:
    - echo "@ubiquity:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">>.npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - echo "always-auth=true">>.npmrc
    - npm install
    - npm run build
    - npm publish
  only:
  - tags
